version: '3.4'

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"

  redis:
    image: redis:alpine
    ports:
      - "5379:6379"   

  zipkin:
    image: openzipkin/zipkin-slim
    ports:
      - "9411:9411"  

  #dashboard:
  #  image: dapr_dashboard_cp:latest
  #  container_name: dashboard
  #  ports:
  #    - "8080:8080"

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=example        
    ports:
      - '5432:5432'

  webapp:
    image: ${DOCKER_REGISTRY-}webapp
    build:
      context: .
      dockerfile: WebApp/Dockerfile

  webapp-dapr:
    image: "daprio/daprd:1.0.0"
    command: [ "./daprd", "-app-id", "webapp", "-app-port", "80","-components-path", "/components", "-config", "/configuration/config.yaml" ]
    depends_on:
      - webapp
    network_mode: "service:webapp"
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    

  webapi-dapr:
    image: "daprio/daprd:1.0.0"
    command: [ "./daprd", "-app-id", "webapi", "-app-port", "80","-components-path", "/components", "-config", "/configuration/config.yaml" ]
    depends_on:
      - webapi
    network_mode: "service:webapi"
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"


  mobileapp:
    image: ${DOCKER_REGISTRY-}mobileapp
    build:
      context: .
      dockerfile: mobileApp/Dockerfile

  mobile-dapr:
    image: "daprio/daprd:1.0.0"
    command: [ "./daprd", "-app-id", "mobileapp", "-app-port", "80","-components-path", "/components", "-config", "/configuration/config.yaml" ]
    depends_on:
      - mobileapp
    network_mode: "service:mobileapp"
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

