apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestoreSql
  namespace: default
spec:
  type: state.sqlserver
  version: v1
  metadata:
  - name: connectionString
    value: "Server=apbadi.database.windows.net;Database=mytestdb;User Id=ap;Password=Password@123;"
  - name: tableName
    value: "stateStore"
  - name: schema
    value: "dbo"
  - name: keyPrefix
    value: MyPrefix
